### ISSUE TITLE
Liveness detection for the interface 

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#109]
- Exit reachability per neighbor: Says whether the selected exit is reachable through the neighbor. Info to come from babel.

```
[
   {
      "nickname": "fd00::2",
      "route_metric_to_exit": 0,
      "exit_reachable": true,
      "total_debt": 0,
      "current_debt": 0,
      "link_cost": 0,
      "price_to_exit": 0
   },
   {
      "nickname": "fd00::7",
      "route_metric_to_exit": 0,
      "exit_reachable": false,
      "total_debt": 0,
      "current_debt": 0,
      "link_cost": 0,
      "price_to_exit": 0
   }
]
```

- Is selected exit reachable: checks whether there is an exit tunnel open. This info comes from wireguard.

```
  "exit_client": {
    "exit_tunnel_working": true,
```

- Is selected exit supplying internet: Poll a hopefully-representative subset of internet domains and see if they are reachable.

```
  "exit_client": {
    "is_selected_exit_online": true,
```

- Exit reachability per exit: Check whether the exit is reachable. Info comes from babel.

```
exits": {
      "apac": {
        "id": {
          "eth_address": "0x0101010101010101010101010101010101010101",
          "mesh_ip": "fd96::1337:e4f",
          "wg_public_key": "1kKSpzdhI4kfqeMqch9I1bXqOUXeKN7EQBecVzW60ys="
        },
       "reachable": true,
        "message": "In Singapore",
        "registration_port": 4875,
        "state": "New"
      },
```

**Comment by kingoflolz** [comment]
@jtremback how do we define exit tunnel working? I don't think wireguard can tell us that info but we can try pinging across the tunnel, the rest seem reasonable

(although I think is_selected_exit_online is a bit redendent, the case where an exit has no internet _and_ can connect to the mesh would be pretty rare, unless something dodgy like someone running an exit on their gateway is happening

**Comment by jtremback** [comment]
@kingoflolz @ttk2 had some more ideas about exit tunnel working. I'm not sure.

**Comment by jkilpatr** [comment]
@kingoflolz we can just check for a handshake on the wireguard tunnel. I spent today trying and failing to fix the wan issues and realizing it's a time pit. So I'll do this tomorrow.

**Comment by kingoflolz** [comment]
@jkilpatr the problem is I remember seeing some old handshake times on working connections, because I think the handshake timer only counts explicit handshakes, not keep alive traffic or anything periodic (so might only be reset on connection disruption), or do you just mean checking if there is _a_ handshake

**Comment by jkilpatr** [comment]
@kingoflolz actually even if the handshake is very old it indicates there has been a connection, the problem is if the interface has not been working for a long time.
