### ISSUE TITLE
Exits never go into pending state

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#110]
It seems that exits never go into "pending" state. Immediately after clicking "connect", I received a `/settings` response that had `"current_exit": "canada east"` and Canada east's state was still "New". Logically, it should have been Pending.

**Comment by kingoflolz** [comment]
We can't connect to the exit when we don't have their information (can't go into pending without gotinfo, so exits with state new should be greyed out in the UI IMO)

**Comment by jtremback** [comment]
But I was able to connect and use the internet from Australia

**Comment by kingoflolz** [comment]
the state enum is decoupled from the information we have (which in hindsight is probs a pretty bad idea), which means that it can get out of sync with the information
although I'm not sure how it would get reset back to New when it already has the info

**Comment by jkilpatr** [comment]
@kingoflolz  is this resolved or waiting on the exit client refactor?

**Comment by kingoflolz** [comment]
waiting on refactor
