### ISSUE TITLE
Exits slowly register themselves

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#112]
Exits go into state "Registered" over the course of a few minutes, without clicking "connect" on any of them. They had been registered to before from the same gateway. This is not neccesarily bad, but unexpected. close this issue if this is ok.

**Comment by kingoflolz** [comment]
They should register to any previous exits that they have been connected to, although it is curious why it takes minutes, it should only take a couple seconds, I'll leave this open for investigation

**Comment by jkilpatr** [comment]
if it's this slow it's either a sync issue or a bug.

**Comment by jkilpatr** [comment]
it seems fast to me. I think this is part of the multi gateway bug, which should be resolved now or soon. Closing.
