### ISSUE TITLE
The API docs are difficult to read - let's group endpoints by service

### ISSUE THREAD

**Issue by drozdziak1** [althea-mesh/althea_rs#113]
# What?
Right now our API is documented with each entrypoint having a file of its own - as we discussed on Riot this isn't very readable, and I proposed an approach where we use bullets instead of gigantic headers and where all entrypoints for a given service are kept in one file -  e.g. for the dashboard, for Rita's common stuff, the client- or exit-specific stuff.

# Why?
That way a newcomer doesn't have to explicitly know what endpoint they want and can easily see all the entrypoints connected to a service they want to interface with. Like with many things, here too the real problems only appear at scale - opening numerous tabs to view one service's docs is going to be a pain.

# How?
We need to go to `exit.rs` and `client.rs` and group the entrypoint docs by the individual HTTP servers we run there (we could come up with another grouping, but please let's not force people to open 10 tabs just for one service we provide). We would go to each per-entrypoint file and gather them and replace headers (`#`) with bullets (`*` or `-`).

**Comment by jkilpatr** [comment]
I think we just fixed this?
