### ISSUE TITLE
Add a /wipe for dev builds

### ISSUE THREAD

**Issue by mpapierski** [althea-mesh/althea_rs#173]
It could be really handy for development to add a `/wipe` HTTP endpoint that would wipe possible state in rita:

- Remove `wg` keys
- Remove `eth` keys

The most important thing to make sure is that this endpoint has to be hidden in release builds. An integration test is welcome that would verify release build doesn't have this endpoint.

It seems perfectly reasonable to add 'dangerous' endpoints during development to speed development.

**Comment by asoltys** [comment]
lgtm. I think putting it in a dev build is a good idea for now. Could think about adding some sort of 2fa challenge in the future if we decide end users might want this kind of thing. For any potentially harmful endpoint actions, prompt the user via email or 2fa app to confirm the action. But for where we're at now that's probably overkill.

**Comment by mpapierski** [comment]
@asoltys interesting idea with 2FA. I'll try to pick up this issue tomorrow. I also agree with your point - dev productivity should be our priority to speed up development.
