### ISSUE TITLE
Determine if KI.open_tunnel can make goo duse of an ifidx

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#176]
After the tunnel manager refactor interface index is now easily available to KI.open_tunnel but the requirements of open tunnel are a little different than just the index, a refactor may be able to take advantage of this information.

**Comment by donkey-hotei** [comment]
This can be closed? https://github.com/althea-mesh/althea_rs/blob/master/rita/src/rita_common/tunnel_manager/mod.rs#L609

**Comment by jkilpatr** [comment]
yes it can!
