### ISSUE TITLE
StarTLS with Lettre fails when using MUSL static builds

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#183]
https://gist.github.com/jkilpatr/c69d57f7bd84cb65847a5ec7e065ec52

**Comment by mpapierski** [comment]
Hey @jkilpatr looks like very important bug to resolve. What are the steps to replicate this problem?

**Comment by mpapierski** [comment]
I mean this might be the solution: https://github.com/emk/rust-musl-builder#making-openssl-work.

**Comment by mpapierski** [comment]
I was able to replicate this issue on musl static builds with a simple `reqwest` HTTPS request. `openssl-probe` appears to be the right solution. Fix is on the way.
