### ISSUE TITLE
Exits Endpoint 504's during exit signup

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#185]
Reported by Adam, I speculate that during the exit state transition there are issues with serialization/deserialization

**Comment by mpapierski** [comment]
Any chance to get logs from the service that would include a backtrace?

**Comment by jkilpatr** [comment]
tried, no interesting backtrace.

**Comment by jkilpatr** [comment]
https://gist.github.com/jkilpatr/0accd8717a679c7f51e3951869c36184

**Comment by jkilpatr** [comment]
@asoltys  is this continuing to cause problems for you?
