### ISSUE TITLE
The integration tests occasionaly fail to let nodes reach the exit's mesh ip

### ISSUE THREAD

**Issue by drozdziak1** [althea-mesh/althea_rs#186]
# Reproducing
Run the integration tests like you would normally do.

# Symptoms
The script says that node 1 can't reach node 5 and exits. **Doesn't always happen on first try, so rerun a few times if you don't get the error**

# Triggering changeset
Justin's `explicit-peer-discovery` refactor branch

# Ideas for fixing this
* Reproduce IRL
* Find out the rate at which the tests fail as opposed to passing

**Comment by mpapierski** [comment]
Like on our meeting today I'd suggest ditching "-s" or "-f" on curl and make sure stderr of that command goes to stdout of test runner to make sure we're able to investigate whats going on. That would at least make it possible to know why exacly it fails. Also we can add connect timeout to curl command so it wont fail immediately (lets say travis has timing/performance problems and that connection just failed for any reason). Retrying curl commands might also work after some small delay.

**Comment by drozdziak1** [comment]
What does curl have to do with any of this in your opinion?

**Comment by jkilpatr** [comment]
I'm not sure what the status of this is after recent changes we should investigate again.
