### ISSUE TITLE
Ethereum transactions research

### ISSUE THREAD

**Issue by mpapierski** [althea-mesh/althea_rs#201]
Figure out how to generate ethereum transactions.

- How to generate a transaction without parity tech?
- What can we do to support ring as our own fork because of upstream developer aren't helpful so far.

**Comment by mpapierski** [comment]
* `parity-crypto` crate depends on ring

Features of ring that it uses (X if it works in our fork, empty if not, or not sure)

- [ ] `aes_gcm`
- [x] `SHA256` `SHA512` - This can be mitigated with making a pull request there to use `multihash` which doesn't use `ring` anymore for the same crypto, nonetheless our fork of ring supports SHA on MIPS just fine.
- [ ] HMAC
- [x] pbkdf2

**Comment by jkilpatr** [comment]
https://github.com/DaGenix/rust-crypto

with this and multihash can we just avoid ring totally? I would feel kinda odd using a special ring pin just for one or two things. But if that's the better way to go we can do it of course. 

Also this all increases the audit surface I'm sure.

**Comment by mpapierski** [comment]
@jkilpatr We could do that too for sure. Not sure how serious is this library (is it used?) in terms of security (i.e. do they use constant time crypto like ring, cleaning up memory safely, etc). I think now `ring` or crypto in general seem to be the smallest problem - deeper I'm going into this it turns out more libs have problem with endianness and mips support. Sometimes totally unrelated problems with architecture in unrelated crates to crypto - like rocksdb.

**Comment by mpapierski** [comment]
(WIP)

# Context

All builds are done on `parity-common` with swapped `ring`:

```diff
diff --git a/parity-crypto/Cargo.toml b/parity-crypto/Cargo.toml
index 5c0af90..fd7dca1 100644
--- a/parity-crypto/Cargo.toml
+++ b/parity-crypto/Cargo.toml
@@ -6,7 +6,7 @@ authors = ["Parity Technologies <admin@parity.io>"]
 [dependencies]
 ethereum-types = "0.3"
 quick-error = "1.2.2"
-ring = "0.12"
+ring = { git = "https://github.com/mpapierski/ring", rev = "ae9d77ca675ac48326dc1d3bbf0f06198339d557" } 
 rust-crypto = "0.2.36"
 tiny-keccak = "1.4"
```

# Build & test

MIPSEL: `cross test --target mipsel-unknown-linux-gnu --no-fail-fast --all --exclude uint --exclude kvdb-rocksdb`
MIPS64EL: `cross test --target mips64el-unknown-linux-gnuabi64 --no-fail-fast --all --exclude uint --exclude kvdb-rocksdb`

Crate | MIPS | MIPS64 | MIPSEL | MIPS64EL
----- | ----- | ----- | ----- | -----
`parity-common` | ? | ? | 1 Test failure[1] | Yes

[1]: https://pastebin.com/vY9ChC3V

**Comment by jkilpatr** [comment]
So the conclusion is that we will have to implement our own Eth transaction generation using the crypto libraries we have ported.

**Comment by jkilpatr** [comment]
Parity people seem at least somewhat interested in fixing this, we'll see how that goes.

**Comment by mpapierski** [comment]
Bunch of new stuff:

# What we need

- `secp256k1` - This seems to be a good start: https://github.com/rust-bitcoin/rust-secp256k1. Similiar to original ethereum impl they link to a libsecp256k1. It might be good idea to test it out with cross compiler, though.
- "Big number" type sort of needed to store "secp256k1n/2". I'd push for `BigUint` from `num-bigint` here as a starter.
- `rlp` encoding to convert tx parameters into a buffer. We may be able to pull this out of `parity`, but its not a rocket science to build our own: https://github.com/ethereum/wiki/wiki/RLP. 

Required parameters of a transaction:

- nonce - transaction sequence number fr the sending account
- gasprice - price you are offering to pay
- startgas - maximum amount of gas allowed for the transaction
- to - destination address (account or contract address)
- value - eth to transfer to the destination, if any
- data - all of the interesting stuff goes here
- v - along with r and s makes up the ECDSA signature
- r
- s

Next step would be to take the encoded parameters and sign it with private key *TODO*.

# What we need

- A good test suite of example parameters of a transaction and their rlp or perhaps already signed parameters that we can test against. I'm almost sure ethereum codebase (or any implementation) has more than enough of test cases we can pull.

# Architecture

I'd propose two APIs: low, and high level. Low would take care of all the tx parameter stuff and encoding it as RLP buffer and higher level stuff would take care of tx `nonce` values, mainnet/testnet parameters, etc and pass it to the low level stuff. That would be easier to unit test.

There is fairly good chance that `clarity` wouldn't need `parity` libs to just sign transactions.

# Resources

- https://ethereum.stackexchange.com/questions/1990/what-is-the-ethereum-transaction-data-structure

**Comment by jkilpatr** [comment]
sounds pretty good to me, what do you think about implementation time?

**Comment by mpapierski** [comment]
@jkilpatr as discussed on Riot we can broke it down into smaller tasks and implement them one by one possibly trying to parallelize things as much as we can. I'll close this research for now.
