### ISSUE TITLE
Run builds with --frozen

### ISSUE THREAD

**Issue by mpapierski** [althea-mesh/althea_rs#206]
This makes better use of `Cargo.lock` features. This way we will make sure that `Cargo.toml` stays in sync with `Cargo.lock` possibly decreasing amount of accidental package updates etc.

# Example

```
λ ~/Projects/althea_rs/ master git status
On branch master
Your branch is up to date with 'upstream/master'.

nothing to commit, working tree clean
λ ~/Projects/althea_rs/ master cargo build --frozen
error: the lock file needs to be updated but --frozen was passed to prevent this
λ ~/Projects/althea_rs/ master cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
λ ~/Projects/althea_rs/ master* cargo build --frozen
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
λ ~/Projects/althea_rs/ master* git status
On branch master
Your branch is up to date with 'upstream/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Cargo.lock
```

# Things to change

- [x] `.travis.yml` for test and build stages.
- [x] Integration tests runner
- [x] Static linux builds in `linux_build_static.sh`
- [x] Per-architecture build scripts

**Comment by jkilpatr** [comment]
while we should generally avoid cargo.lock updates when we don't need them they are required frequently enough that I'm not sure this is worth it.
