### ISSUE TITLE
Reactor performance

### ISSUE THREAD

**Issue by mpapierski** [althea-mesh/althea_rs#209]
Investigate possible causes of reactor slow downs. Especially after reboots it takes longer to complete requests to dashboard API.

Possible causes that we can handle:

* Babel calls are blocking the reactor - According to @ttk2 measurements it usually takes 50ms on average to complete those calls. It'd be interesting to measure P90, P99s.
* General system slowdown after a boot caused to flash I/O, etc.
* Blocking calls such as pings that can timeout after some time therefore blocking whole reactor.
* StatsCollector uses blocking calls #220 

It would be good idea to add more insights to the code to better measure time spent in different parts of the code. From that point we can better know what decision should we make.

**Comment by jkilpatr** [comment]
yes this seems resolved now.
