### ISSUE TITLE
Exits sometimes go back to 'Registered' state after being Reset

### ISSUE THREAD

**Issue by asoltys** [althea-mesh/althea_rs#226]
I've noticed that sometimes when I reset an exit that I've successfully registered for, the state will go to "New" for a moment but then go back to "Registered' after a few seconds. If I try resetting again, sometimes 2 or 3 times, I can eventually get it to work and the exit will stay in the GotInfo state.

**Comment by jtremback** [comment]
We had this discussion before in the forum- the exit doesn't know that you have reset it, resetting is purely done on your router. You are in fact still registered with the exit. What's puzzling to me is that it does go back to GotInfo at all.
