### ISSUE TITLE
Use meshpoint instead of adhoc for peer to peer radio mode 

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#248]
We have a 'mesh' toggle in the wifi settings to allow the use of an internal radio for direct connections, adhoc is so unreliable it's almost useless though, hopefully 'meshpoint' (802.11s) works better @NukeManDan is investigating on rpi's with meshpoint support. Hopefully he can report results here.

**Comment by NukeManDan** [comment]
So first - bad new is that onboard hardware w/ standard drivers on RPi 3B+  does NOT support 802.11s .
RPI 3B _might_ support it in a limited fashion. A (relatively) cheap USB adapter can be used though, so for a hardware fix is avalible for almost any other machines beyond the pi that do not have onboard 802.11s support.  

The work I am basing this off of:
- https://github.com/tomeshnet/prototype-cjdns-pi
- https://github.com/phillymesh/802.11s-adapters  (list all RPis and know capabilities) 

Running list of adapter and notes on them:
- https://github.com/phillymesh/802.11s-adapters

---

Good news - I am investigating a possible solution:
- https://github.com/o11s/open80211s/
- https://github.com/o11s/open80211s/wiki/HOWTO

>open80211s relies on Linux's [mac80211]

This depends on the hardware being SoftMAC/ I am looking into if this is possible for RPis presently.
