### ISSUE TITLE
num256 needs a math review

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#25]

**Comment by jtremback** [comment]
@mpapierski The only real purpose of this library is to panic on overflow. Do you not feel that this is important?

**Comment by jtremback** [comment]
For instance, without overflow checking, I could cause my channel counterparty to believe that an update that will end up overflowing and throwing on the chain is valid. Perhaps they might then garbage collect their old updates. This would leave them unable to settle and vulnerable to an old update attack.

We could overflow check elsewhere, but why? Checking in the number lib seems much cleaner. Using this num256 library also gives us the flexibility to possibly switch to an optimized implementation on some platforms instead of just wrapping the bigint stuff.

**Comment by mpapierski** [comment]
@jtremback You're right and I agree that we should do overflowing checks to keep it consistent with Ethereum's data types.

While playing with num256 I think I saw place where we mix Int256 and Uint256 - where normally rust forbids math on i32 and u32. Its potentially unsafe as there may be involved implicit conversion. I think a review of num256 usage would also improve stability.

**Comment by jtremback** [comment]
@mpapierski good catch- do you remember where?
