### ISSUE TITLE
Exits should indicate if an email is or is not mandatory

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/althea_rs#279]
Just need to fix tests for this one.

Right now it's possible to have exits that don't need emails, but the UI will always assume that one is needed because it can't be sure without trying. 
The exit should include in it's exit details struct if an email is or is not required. This will then be exposed from the exits endpoint to the UI which can take advantage of it. 

this is pretty low priority. Might be a good task for @asoltys rust wise if he has free time.

**Comment by jkilpatr** [comment]
just add 'needs email' to the exit details struct.

**Comment by drozdziak1** [comment]
Deadline estimated to **Thursday afternoon**
