### ISSUE TITLE
Implement router-dao address exchange

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#309]
Check out this post: https://forum.altheamesh.com/t/router-to-subnet-dao-data-exchange-setup/169

And talk to jehan before starting

**Comment by asoltys** [comment]
This was mostly a front end issue, solved by https://github.com/althea-mesh/althea-dash/pull/33 and requiring HTTPS implemented by https://github.com/althea-mesh/althea_rs/pull/323
