### ISSUE TITLE
Start thinking about changing "debt" from one int to two uints

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#38]
eg:
"i_owe_them", "they_owe_me"
"credit", "debt"

**Comment by jkilpatr** [comment]
what was done about this? should we close it?

**Comment by kingoflolz** [comment]
this is a pretty low priority issue as we will be changing something which is working and basically feature complete for the sake of readability

**Comment by jtremback** [comment]
Yea this is from way back when. it was basically intended to be a design discussion but we just ended up sticking with what I had implemented in the beginning
