### ISSUE TITLE
Neighbor discovery 

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/althea_rs#6]
Nodes need to be able to find each other over the local link and exchange information to be able to participate in Althea. Right now the information to be exchanged is an Identity:

```
Identity {
  ip_address,
  eth_address,
  mac_address
}
```

We have been relying on shelling out to the `ip neigh` command to find neighbors. Sometimes this will give us neighbor's mesh IP address (as opposed to only their link-local IP). When it works, it looks like this:

```
$ ip netns exec netlab-2 ip neighbor
2001::1 dev br-2-1 lladdr 56:77:b0:f5:1f:bc router STALE
fe80::5477:b0ff:fef5:1fbc dev br-2-1 lladdr 56:77:b0:f5:1f:bc router STALE
fe80::b0c2:14ff:fe8d:a838 dev br-2-3 lladdr b2:c2:14:8d:a8:38 router STALE
2001::3 dev br-2-3 lladdr b2:c2:14:8d:a8:38 router STALE
```

This is the result of running the command on node 2 on a network like `1--2--3`. It has found the IP addresses and MAC addresses of nodes 1 and 3. It has also found their link-local addresses. By filtering out the link-local addresses, we have the IP addresses and MAC addresses of both neighbors. Each of these can then be contacted at their IP address to get their Eth address, and a complete Identity can be built from this. 

But this is unreliable. Most of the time it will only give us the link-local IP, not showing the mesh IP. 

```
$ ip -6 netns exec netlab-2 ip neighbor
fe80::5477:b0ff:fef5:1fbc dev br-2-1 lladdr 56:77:b0:f5:1f:bc router REACHABLE
fe80::b0c2:14ff:fe8d:a838 dev br-2-3 lladdr b2:c2:14:8d:a8:38 router STALE
```

1. Maybe it is possible to force a refresh of the cache. We have tried using `ndsend` to manually broadcast ICMPv6 router advertisement messages, but these don't seem to affect the output. We have also tried pinging the broadcast address on an interface to get the `ip neigh` cache to refresh, but this doesn't work either. We've also been told by people in various IRC channels that it's not a good idea to use ICMPv6 for this purpose in general.

2. The obvious solution is to contact these neighbors at their link-local IP and ask for their whole Identity, thereby getting their mesh IP. However, we are using HTTP to implement our APIs, and most HTTP libraries use Firefox's URL parser, which does not recognize link-local IP's as being valid (the crux of the issue is that you need to specify a "scope" or network interface to be able to use a link-local address, and the URL parser does not recognize the standard syntax for specifying this in a URL: https://github.com/servo/rust-url/issues/424).

However, the Rust stdlib does have a struct `SocketAddrV6` which contains a field `scope_id: u32`. This will accept the interface index (not the interface name you usually use) and a link-local IP. This can then be passed into Rust's `TcpStream` and used to make a TCP connection with the neighbor. This connection can then be used to send over the Identity, at which point we can use the included mesh IP for further communication.

3. Another option is to skip this step, and use another neighbor discovery protocol. There are many options.
- Babel includes a neighbor discovery protocol, we could increase the information output by babel and get the addresses this way.
- mdns and upnp are two existing neighbor discovery protocols. We could use Rust implementations of theses or shell out to their linux daemons.
- We could roll our own multicast UDP neighbor discovery protocol. We have already done some of this work in the old Go code.

These options seem possibly more robust, but it would still be a good idea to figure out how to talk to link-local addresses since they are heavily used by babel and other software. If we do this, then it might be easier to just do option 2 for now.

**Comment by kingoflolz** [comment]
should we close this since we have a solution in place or should we keep it open for possibly less hacky solutions in the future?

**Comment by jkilpatr** [comment]
What exactly is the current solution? We went with the interface index and the raw tcp library right?

**Comment by jtremback** [comment]
Dunno, the only hacky thing about this is the fact that we are using `ip neigh`

**Comment by kingoflolz** [comment]
We will need to have a neighbor hello or something like that even if we can get `ip neigh` to work "properly" (give us the mesh IP address), so I guess the current solution isn't that hacky.
